name: Electron app builder


on:
  workflow_dispatch:
    inputs:
      node_version:
        description: 'Node version'
        type: string
        default: 18.x

jobs:
  build-mac:
    runs-on: macOS-latest
    name: Build on MacOS
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ github.event.inputs.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ github.event.inputs.node_version }}
      - run: npm ci
      - run: npm run package-electron
      - run: npm run make-electron
      - uses: actions/upload-artifact@v4
        with:
          name: schemio-electron-mac-zip
          path: out/make/zip/darwin/x64/schemio-darwin-arm64-*.zip
      - run: find out | grep -v .webpack/renderer/assets



  build-linux:
    runs-on: ubuntu-latest
    name: Build on Linux
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ github.event.inputs.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ github.event.inputs.node_version }}
      - run: npm ci
      - run: npm run package-electron
      - run: npm run make-electron
      - uses: actions/upload-artifact@v4
        with:
          name: schemio-electron-linux-rpm
          path: out/make/rpm/x64/schemio-*-1.x86_64.rpm
      - uses: actions/upload-artifact@v4
        with:
          name: schemio-electron-linux-deb
          path: out/make/deb/x64/schemio_*_amd64.deb
      - run: find out | grep -v .webpack/renderer/assets

  build-win:
    name: Build Windows app
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ github.event.inputs.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ github.event.inputs.node_version }}
      - run: npm ci
      - run: npm run package-electron
      - run: npm run make-electron
      - uses: actions/upload-artifact@v4
        with:
          name: schemio-electron-win-setup
          path: out/make/squirrel.windows/x64/schemio-* Setup.exe
      - run: npm install -g tree-cli
      - run: cd out && tree -l 8
